import { getProgress } from './storage';
import { getStreak } from './streakSystem';
import { checkAchievements } from './achievements';
import { getPuzzlesByLevel } from './gameLogic';
import { getPerformanceSummary } from './adaptiveDifficulty';

/**
 * Export progress as text report
 */
export const exportProgressReport = async () => {
  try {
    const progress = await getProgress();
    const streak = await getStreak();
    const achievements = await checkAchievements();
    const beginnerPerf = await getPerformanceSummary('beginner');
    const intermediatePerf = await getPerformanceSummary('intermediate');
    const advancedPerf = await getPerformanceSummary('advanced');

    let report = '🧩 PUZZLE FUN - PROGRESS REPORT\n';
    report += '='.repeat(40) + '\n\n';
    report += `Generated: ${new Date().toLocaleString()}\n\n`;

    // Overall Stats
    report += '📊 OVERALL STATISTICS\n';
    report += '-'.repeat(40) + '\n';
    
    let totalCompleted = 0;
    let totalStars = 0;
    const levels = ['beginner', 'intermediate', 'advanced'];
    
    for (const level of levels) {
      const puzzles = getPuzzlesByLevel(level);
      const levelProgress = progress[level] || { completed: [], stars: {} };
      totalCompleted += levelProgress.completed?.length || 0;
      const stars = Object.values(levelProgress.stars || {}).reduce((sum, s) => sum + s, 0);
      totalStars += stars;
    }
    
    report += `Total Puzzles Completed: ${totalCompleted}\n`;
    report += `Total Stars Earned: ${totalStars}\n`;
    report += `Achievements Unlocked: ${achievements.length}\n`;
    report += `Current Streak: ${streak.currentStreak} days\n`;
    report += `Longest Streak: ${streak.longestStreak} days\n\n`;

    // Level Progress
    report += '📚 LEVEL PROGRESS\n';
    report += '-'.repeat(40) + '\n';
    
    for (const level of levels) {
      const puzzles = getPuzzlesByLevel(level);
      const levelProgress = progress[level] || { completed: [], stars: {} };
      const completed = levelProgress.completed?.length || 0;
      const percentage = puzzles.length > 0 ? Math.round((completed / puzzles.length) * 100) : 0;
      const levelName = level.charAt(0).toUpperCase() + level.slice(1);
      
      report += `${levelName}: ${completed}/${puzzles.length} (${percentage}%)\n`;
    }
    
    report += '\n';

    // Performance Summary
    report += '⚡ PERFORMANCE SUMMARY\n';
    report += '-'.repeat(40) + '\n';
    
    if (beginnerPerf) {
      report += `Beginner: ${beginnerPerf.successRate}% success, ${beginnerPerf.avgTime}s avg, ${beginnerPerf.skillLevel} skill\n`;
    }
    if (intermediatePerf) {
      report += `Intermediate: ${intermediatePerf.successRate}% success, ${intermediatePerf.avgTime}s avg, ${intermediatePerf.skillLevel} skill\n`;
    }
    if (advancedPerf) {
      report += `Advanced: ${advancedPerf.successRate}% success, ${advancedPerf.avgTime}s avg, ${advancedPerf.skillLevel} skill\n`;
    }
    
    report += '\n';

    // Achievements
    if (achievements.length > 0) {
      report += '🏆 ACHIEVEMENTS UNLOCKED\n';
      report += '-'.repeat(40) + '\n';
      achievements.forEach(achievement => {
        report += `${achievement.emoji} ${achievement.name}: ${achievement.description}\n`;
      });
      report += '\n';
    }

    // Footer
    report += '='.repeat(40) + '\n';
    report += 'Generated by Puzzle Fun App\n';
    report += 'All data is stored locally on your device.\n';

    return report;
  } catch (error) {
    console.error('Error exporting progress:', error);
    return 'Error generating report. Please try again.';
  }
};

/**
 * Share progress report (for future implementation)
 */
export const shareProgressReport = async () => {
  try {
    const report = await exportProgressReport();
    // In a real app, you would use React Native's Share API here
    // import { Share } from 'react-native';
    // await Share.share({ message: report });
    return report;
  } catch (error) {
    console.error('Error sharing progress:', error);
    return null;
  }
};

